export enum EvaluationType {
  RAG = "RAG",
  Chatbot = "Chatbot",
  Converter = "Converter",
  Classifier = "Classifier",
  RecommendationEngine = "RecommendationEngine",
  Summarization = "Summarization",
  AnomalyDetection = "AnomalyDetection",
  Translation = "Translation",
  TextGeneration = "TextGeneration",
  SpeechRecognition = "SpeechRecognition",
  ImageRecognition = "ImageRecognition",
  PredictiveAnalytics = "PredictiveAnalytics",
  SpeechSynthesis = "SpeechSynthesis",
  SentimentAnalysis = "SentimentAnalysis",
  VisualQuestionAnswering = "VisualQuestionAnswering",
  ComplianceMonitoring = "ComplianceMonitoring",
  HealthMonitoring = "HealthMonitoring",
}

export const evaluationTypesSelector = [
  { id: EvaluationType.RAG, name: "RAG" },
  { id: EvaluationType.Chatbot, name: "Chatbot" },
  { id: EvaluationType.Converter, name: "Converter" },
  { id: EvaluationType.Classifier, name: "Classifier" },
  { id: EvaluationType.RecommendationEngine, name: "Recommendation Engine" },
  { id: EvaluationType.Summarization, name: "Summarization" },
  { id: EvaluationType.AnomalyDetection, name: "Anomaly Detection" },
  { id: EvaluationType.Translation, name: "Translation" },
  { id: EvaluationType.TextGeneration, name: "Text Generation" },
  { id: EvaluationType.SpeechRecognition, name: "Speech Recognition" },
  { id: EvaluationType.ImageRecognition, name: "Image Recognition" },
  { id: EvaluationType.PredictiveAnalytics, name: "Predictive Analytics" },
  { id: EvaluationType.SpeechSynthesis, name: "Speech Synthesis" },
  { id: EvaluationType.SentimentAnalysis, name: "Sentiment Analysis" },
  { id: EvaluationType.VisualQuestionAnswering, name: "Visual Question Answering" },
  { id: EvaluationType.ComplianceMonitoring, name: "Compliance Monitoring" },
  { id: EvaluationType.HealthMonitoring, name: "Health Monitoring" },
];
